version: '3'
services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data/:/var/lib/mysql/

